/*
 * TestCaseUpdater.java
 *
 * Created on July 11, 2008, 5:59 PM
 */

package sbml.test;

/**
 *
 * @author  Kimberly Begley
 * @version 2.0
 */
public class TestCaseUpdater extends javax.swing.JDialog {

    /** Creates new form TestCaseUpdater */
    public TestCaseUpdater(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setVisible(true);
    }

    public void checkForUpdates() {
        UpdateDownloader ud = new UpdateDownloader(this);
        ud.start();
    
    }

    void appendToLog(String string) {
        jTextArea1.append(string);
    }

    void setFinished(String message) {
        jProgressBar1.setIndeterminate(false);
        jProgressBar1.setMaximum(100);
        jProgressBar1.setValue(100);
        jProgressBar1.setString(message);
        jProgressBar1.setStringPainted(true);
    }

    void setLocalTimestamp(String ts) {
        currentVersionLabel.setText(ts);
    }

    void setNewTimestamp(String logLine) {
        latestVersionLabel.setText(logLine);
    }
    
    void setProgressBarIndeterminate(boolean ind) {
        jProgressBar1.setStringPainted(!ind);
        jProgressBar1.setIndeterminate(ind);
    }

    void setProgressBarMax(int i) {
        jProgressBar1.setMaximum(i);
        jProgressBar1.setString("0 MB of "+i/(1024*1024)+" MB");
        jProgressBar1.setStringPainted(true);
    }
    
    void setProgressBarProgress(int i) {
        jProgressBar1.setValue(i);
        jProgressBar1.setString(i/(1024*1024)+" MB of "+jProgressBar1.getMaximum()/(1024*1024)+" MB");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        currentVersionLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        latestVersionLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jLabel1.setText("current version");
        jPanel1.add(jLabel1);

        currentVersionLabel.setText("--");
        jPanel1.add(currentVersionLabel);

        jLabel3.setText("latest version");
        jPanel1.add(jLabel3);

        latestVersionLabel.setText("--");
        jPanel1.add(latestVersionLabel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout(10, 10));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel2.add(jProgressBar1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Cancel button selected
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentVersionLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel latestVersionLabel;
    // End of variables declaration//GEN-END:variables

}
