//
//
// Created by Kimberly Begley
// TestResultDetails
// Data structure and methods for the result generated by the test-suite
// Lots to be added here


package sbml.test;
import java.math.*;

public class TestResultDetails {
	// the TestResultDetails class has 4 fields
	private int result;
	private String testname;
	private String description;
	private String warnings;
	private String plot;
	

	// the TestResultDetails class has one constructor
	public TestResultDetails(int output, String name, String desc, String warning, String plot_path) {
		result = output;
		testname = name;
		description = desc;
		warnings = warning;
		plot = plot_path;
	}

	// the TestResultDetails class has 4 methods
	public void setResult(int newValue) {
		result = newValue;
	}
	public void setTestname(String newValue) {
		testname = newValue;
	}
	public void setWarnings(String newValue) {
		warnings = newValue;
	}
	public void setDescription(String newValue) {
		description = newValue;
	}
	public void setPlot(String newValue) {
		plot = newValue;
	}
	
	public int getResult() {
		return result;
	}
	public String getTestname() {
		return testname;
	}
	public String getWarnings() {
		return warnings;
	}
	public String getPlot() {
		return plot;
	}
	public String getDescription() {
		return description;
	}
		
}
