m=SBMLRead["compartments-nonUnitVolume-initialAmount-l2.xml", context->"None"]
r=SBMLNDSolve[m,5, AccuracyGoal->30, PrecisionGoal->12]
p=SBMLPlot[r]
Export["compartments-nonUnitVolume-initialAmount.GIF",p,ImageSize->750]
plog=SBMLPlot[r, type->"Log"]
Export["compartments-nonUnitVolume-initialAmount-log.GIF",plog,ImageSize->750]
SBMLWrite[inputfile->"compartments-nonUnitVolume-initialAmount-l2.xml", outputfile->"compartments-nonUnitVolume-initialAmount.html", format->"html"]
results = Table[Flatten[{t, N /@ ({S1[t], S2[t] } /. r)}], {t, 0, 5, 0.1}]
results = Prepend[results, {"time", "S1", "S2"}]
Export["compartments-nonUnitVolume-initialAmount.CSV", results]

