m=SBMLRead["algebraicRules-fastReactionExample-l2.xml", context->"SBML"]
r=SBMLNDSolve[m,40, AccuracyGoal->11, PrecisionGoal->12]
p=SBMLPlot[r]
Export["algebraicRules-fastReactionExample.GIF",p,ImageSize->750]
plog=SBMLPlot[r, type->"Log"]
Export["algebraicRules-fastReactionExample-log.GIF",plog,ImageSize->750]
SBMLWrite[inputfile->"algebraicRules-fastReactionExample-l2.xml", outputfile->"algebraicRules-fastReactionExample.html", format->"html"]
results = Table[Flatten[{t, N /@ ({SBML`X0[t], SBML`X1[t], SBML`T[t], SBML`S1[t], SBML`S2[t] } /. r)}], {t, 0, 40, 0.8}]
results = Prepend[results, {"time", "X0", "X1", "T", "S1", "S2"}]
Export["algebraicRules-fastReactionExample.CSV", results]
